function xd = pend(t, x, g,l,mass, IB, a,b,c)

IBxx = IB(1);
IByy = IB(2);
IBzz = IB(3);
IBxy = IB(6);
IByz = IB(4);
IBzx = IB(5);
q1 = x(1);
q2 = x(2);
q3 = x(3);
u1 = x(4);
u2 = x(5);
u3 = x(6);
c1 = c(1);
c2 = c(2);
c3 = c(3);

xd = zeros(6,1);

mm = [
1, 0, 0,                                                                                                                                                                                                                                                                                                                                                                   0,                                                                                                                                                                                                                                                                                                              0,                                                                                                                                            0;
0, 1, 0,                                                                                                                                                                                                                                                                                                                                                                   0,                                                                                                                                                                                                                                                                                                              0,                                                                                                                                            0;
0, 0, 1,                                                                                                                                                                                                                                                                                                                                                                   0,                                                                                                                                                                                                                                                                                                              0,                                                                                                                                            0;
0, 0, 0, mass*((-a*sin(q2) + l*cos(q2)*cos(q3))^2 + (b*sin(q2) + l*sin(q3)*cos(q2))^2 + (-a*sin(q3)*cos(q2) - b*cos(q2)*cos(q3))^2) + (IBxx*cos(q2)*cos(q3) - IBxy*sin(q3)*cos(q2) + IBzx*sin(q2))*cos(q2)*cos(q3) - (IBxy*cos(q2)*cos(q3) - IByy*sin(q3)*cos(q2) + IByz*sin(q2))*sin(q3)*cos(q2) + (-IByz*sin(q3)*cos(q2) + IBzx*cos(q2)*cos(q3) + IBzz*sin(q2))*sin(q2), mass*(l*(-a*sin(q2) + l*cos(q2)*cos(q3))*sin(q3) - l*(b*sin(q2) + l*sin(q3)*cos(q2))*cos(q3) + (a*cos(q3) - b*sin(q3))*(-a*sin(q3)*cos(q2) - b*cos(q2)*cos(q3))) + (IBxx*cos(q2)*cos(q3) - IBxy*sin(q3)*cos(q2) + IBzx*sin(q2))*sin(q3) + (IBxy*cos(q2)*cos(q3) - IByy*sin(q3)*cos(q2) + IByz*sin(q2))*cos(q3), -IByz*sin(q3)*cos(q2) + IBzx*cos(q2)*cos(q3) + IBzz*sin(q2) + mass*(-a*(-a*sin(q2) + l*cos(q2)*cos(q3)) + b*(b*sin(q2) + l*sin(q3)*cos(q2)));
0, 0, 0,                                                            mass*(l*(-a*sin(q2) + l*cos(q2)*cos(q3))*sin(q3) - l*(b*sin(q2) + l*sin(q3)*cos(q2))*cos(q3) + (a*cos(q3) - b*sin(q3))*(-a*sin(q3)*cos(q2) - b*cos(q2)*cos(q3))) + (IBxx*sin(q3) + IBxy*cos(q3))*cos(q2)*cos(q3) - (IBxy*sin(q3) + IByy*cos(q3))*sin(q3)*cos(q2) + (IByz*cos(q3) + IBzx*sin(q3))*sin(q2),                                                                                                                                                          mass*(l^2*sin(q3)^2 + l^2*cos(q3)^2 + (a*cos(q3) - b*sin(q3))^2) + (IBxx*sin(q3) + IBxy*cos(q3))*sin(q3) + (IBxy*sin(q3) + IByy*cos(q3))*cos(q3),                                                                              IByz*cos(q3) + IBzx*sin(q3) + mass*(-a*l*sin(q3) - b*l*cos(q3));
0, 0, 0,                                                                                                                                                                                                                        -IByz*sin(q3)*cos(q2) + IBzx*cos(q2)*cos(q3) + IBzz*sin(q2) + mass*(-a*(-a*sin(q2) + l*cos(q2)*cos(q3)) + b*(b*sin(q2) + l*sin(q3)*cos(q2))),                                                                                                                                                                                                                                                IByz*cos(q3) + IBzx*sin(q3) + mass*(-a*l*sin(q3) - b*l*cos(q3)),                                                                                                                    IBzz + mass*(a^2 + b^2)];


fo = [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   u1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   u2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   u3;
-c1*u1*cos(q2)*cos(q3) + c2*u2*sin(q3)*cos(q2) - c3*u3*sin(q2) - g*mass*(-a*sin(q2) + l*cos(q2)*cos(q3))*(sin(q1)*cos(q3) + sin(q2)*sin(q3)*cos(q1)) - g*mass*(b*sin(q2) + l*sin(q3)*cos(q2))*(sin(q1)*sin(q3) - sin(q2)*cos(q1)*cos(q3)) - g*mass*(-a*sin(q3)*cos(q2) - b*cos(q2)*cos(q3))*cos(q1)*cos(q2) - mass*(-a*sin(q2) + l*cos(q2)*cos(q3))*(-a*u1*u2*cos(q2) + l*(-u1*u2*sin(q2)*cos(q3) - u1*u3*sin(q3)*cos(q2) + u2*u3*cos(q3)) - (a*(-u1*sin(q3)*cos(q2) + u2*cos(q3)) - b*(u1*cos(q2)*cos(q3) + u2*sin(q3)))*(u1*cos(q2)*cos(q3) + u2*sin(q3)) + (b*(u1*sin(q2) + u3) - l*(-u1*sin(q3)*cos(q2) + u2*cos(q3)))*(u1*sin(q2) + u3)) - mass*(b*sin(q2) + l*sin(q3)*cos(q2))*(b*u1*u2*cos(q2) - l*(u1*u2*sin(q2)*sin(q3) - u1*u3*cos(q2)*cos(q3) - u2*u3*sin(q3)) - (-a*(u1*sin(q2) + u3) + l*(u1*cos(q2)*cos(q3) + u2*sin(q3)))*(u1*sin(q2) + u3) + (a*(-u1*sin(q3)*cos(q2) + u2*cos(q3)) - b*(u1*cos(q2)*cos(q3) + u2*sin(q3)))*(-u1*sin(q3)*cos(q2) + u2*cos(q3))) - mass*(-a*sin(q3)*cos(q2) - b*cos(q2)*cos(q3))*(a*(u1*u2*sin(q2)*sin(q3) - u1*u3*cos(q2)*cos(q3) - u2*u3*sin(q3)) - b*(-u1*u2*sin(q2)*cos(q3) - u1*u3*sin(q3)*cos(q2) + u2*u3*cos(q3)) + (-a*(u1*sin(q2) + u3) + l*(u1*cos(q2)*cos(q3) + u2*sin(q3)))*(u1*cos(q2)*cos(q3) + u2*sin(q3)) - (b*(u1*sin(q2) + u3) - l*(-u1*sin(q3)*cos(q2) + u2*cos(q3)))*(-u1*sin(q3)*cos(q2) + u2*cos(q3))) - (IBxx*(-u1*u2*sin(q2)*cos(q3) - u1*u3*sin(q3)*cos(q2) + u2*u3*cos(q3)) + IBxy*(u1*u2*sin(q2)*sin(q3) - u1*u3*cos(q2)*cos(q3) - u2*u3*sin(q3)) + IBzx*u1*u2*cos(q2) - (u1*sin(q2) + u3)*(IBxy*(u1*cos(q2)*cos(q3) + u2*sin(q3)) + IByy*(-u1*sin(q3)*cos(q2) + u2*cos(q3)) + IByz*(u1*sin(q2) + u3)) + (-u1*sin(q3)*cos(q2) + u2*cos(q3))*(IByz*(-u1*sin(q3)*cos(q2) + u2*cos(q3)) + IBzx*(u1*cos(q2)*cos(q3) + u2*sin(q3)) + IBzz*(u1*sin(q2) + u3)))*cos(q2)*cos(q3) + (IBxy*(-u1*u2*sin(q2)*cos(q3) - u1*u3*sin(q3)*cos(q2) + u2*u3*cos(q3)) + IByy*(u1*u2*sin(q2)*sin(q3) - u1*u3*cos(q2)*cos(q3) - u2*u3*sin(q3)) + IByz*u1*u2*cos(q2) + (u1*sin(q2) + u3)*(IBxx*(u1*cos(q2)*cos(q3) + u2*sin(q3)) + IBxy*(-u1*sin(q3)*cos(q2) + u2*cos(q3)) + IBzx*(u1*sin(q2) + u3)) - (u1*cos(q2)*cos(q3) + u2*sin(q3))*(IByz*(-u1*sin(q3)*cos(q2) + u2*cos(q3)) + IBzx*(u1*cos(q2)*cos(q3) + u2*sin(q3)) + IBzz*(u1*sin(q2) + u3)))*sin(q3)*cos(q2) - (IByz*(u1*u2*sin(q2)*sin(q3) - u1*u3*cos(q2)*cos(q3) - u2*u3*sin(q3)) + IBzx*(-u1*u2*sin(q2)*cos(q3) - u1*u3*sin(q3)*cos(q2) + u2*u3*cos(q3)) + IBzz*u1*u2*cos(q2) - (-u1*sin(q3)*cos(q2) + u2*cos(q3))*(IBxx*(u1*cos(q2)*cos(q3) + u2*sin(q3)) + IBxy*(-u1*sin(q3)*cos(q2) + u2*cos(q3)) + IBzx*(u1*sin(q2) + u3)) + (u1*cos(q2)*cos(q3) + u2*sin(q3))*(IBxy*(u1*cos(q2)*cos(q3) + u2*sin(q3)) + IByy*(-u1*sin(q3)*cos(q2) + u2*cos(q3)) + IByz*(u1*sin(q2) + u3)))*sin(q2);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           -c1*u1*sin(q3) - c2*u2*cos(q3) + g*l*mass*(sin(q1)*sin(q3) - sin(q2)*cos(q1)*cos(q3))*cos(q3) - g*l*mass*(sin(q1)*cos(q3) + sin(q2)*sin(q3)*cos(q1))*sin(q3) - g*mass*(a*cos(q3) - b*sin(q3))*cos(q1)*cos(q2) - l*mass*(-a*u1*u2*cos(q2) + l*(-u1*u2*sin(q2)*cos(q3) - u1*u3*sin(q3)*cos(q2) + u2*u3*cos(q3)) - (a*(-u1*sin(q3)*cos(q2) + u2*cos(q3)) - b*(u1*cos(q2)*cos(q3) + u2*sin(q3)))*(u1*cos(q2)*cos(q3) + u2*sin(q3)) + (b*(u1*sin(q2) + u3) - l*(-u1*sin(q3)*cos(q2) + u2*cos(q3)))*(u1*sin(q2) + u3))*sin(q3) + l*mass*(b*u1*u2*cos(q2) - l*(u1*u2*sin(q2)*sin(q3) - u1*u3*cos(q2)*cos(q3) - u2*u3*sin(q3)) - (-a*(u1*sin(q2) + u3) + l*(u1*cos(q2)*cos(q3) + u2*sin(q3)))*(u1*sin(q2) + u3) + (a*(-u1*sin(q3)*cos(q2) + u2*cos(q3)) - b*(u1*cos(q2)*cos(q3) + u2*sin(q3)))*(-u1*sin(q3)*cos(q2) + u2*cos(q3)))*cos(q3) - mass*(a*cos(q3) - b*sin(q3))*(a*(u1*u2*sin(q2)*sin(q3) - u1*u3*cos(q2)*cos(q3) - u2*u3*sin(q3)) - b*(-u1*u2*sin(q2)*cos(q3) - u1*u3*sin(q3)*cos(q2) + u2*u3*cos(q3)) + (-a*(u1*sin(q2) + u3) + l*(u1*cos(q2)*cos(q3) + u2*sin(q3)))*(u1*cos(q2)*cos(q3) + u2*sin(q3)) - (b*(u1*sin(q2) + u3) - l*(-u1*sin(q3)*cos(q2) + u2*cos(q3)))*(-u1*sin(q3)*cos(q2) + u2*cos(q3))) - (IBxx*(-u1*u2*sin(q2)*cos(q3) - u1*u3*sin(q3)*cos(q2) + u2*u3*cos(q3)) + IBxy*(u1*u2*sin(q2)*sin(q3) - u1*u3*cos(q2)*cos(q3) - u2*u3*sin(q3)) + IBzx*u1*u2*cos(q2) - (u1*sin(q2) + u3)*(IBxy*(u1*cos(q2)*cos(q3) + u2*sin(q3)) + IByy*(-u1*sin(q3)*cos(q2) + u2*cos(q3)) + IByz*(u1*sin(q2) + u3)) + (-u1*sin(q3)*cos(q2) + u2*cos(q3))*(IByz*(-u1*sin(q3)*cos(q2) + u2*cos(q3)) + IBzx*(u1*cos(q2)*cos(q3) + u2*sin(q3)) + IBzz*(u1*sin(q2) + u3)))*sin(q3) - (IBxy*(-u1*u2*sin(q2)*cos(q3) - u1*u3*sin(q3)*cos(q2) + u2*u3*cos(q3)) + IByy*(u1*u2*sin(q2)*sin(q3) - u1*u3*cos(q2)*cos(q3) - u2*u3*sin(q3)) + IByz*u1*u2*cos(q2) + (u1*sin(q2) + u3)*(IBxx*(u1*cos(q2)*cos(q3) + u2*sin(q3)) + IBxy*(-u1*sin(q3)*cos(q2) + u2*cos(q3)) + IBzx*(u1*sin(q2) + u3)) - (u1*cos(q2)*cos(q3) + u2*sin(q3))*(IByz*(-u1*sin(q3)*cos(q2) + u2*cos(q3)) + IBzx*(u1*cos(q2)*cos(q3) + u2*sin(q3)) + IBzz*(u1*sin(q2) + u3)))*cos(q3);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       -IByz*(u1*u2*sin(q2)*sin(q3) - u1*u3*cos(q2)*cos(q3) - u2*u3*sin(q3)) - IBzx*(-u1*u2*sin(q2)*cos(q3) - u1*u3*sin(q3)*cos(q2) + u2*u3*cos(q3)) - IBzz*u1*u2*cos(q2) + a*g*mass*(sin(q1)*cos(q3) + sin(q2)*sin(q3)*cos(q1)) + a*mass*(-a*u1*u2*cos(q2) + l*(-u1*u2*sin(q2)*cos(q3) - u1*u3*sin(q3)*cos(q2) + u2*u3*cos(q3)) - (a*(-u1*sin(q3)*cos(q2) + u2*cos(q3)) - b*(u1*cos(q2)*cos(q3) + u2*sin(q3)))*(u1*cos(q2)*cos(q3) + u2*sin(q3)) + (b*(u1*sin(q2) + u3) - l*(-u1*sin(q3)*cos(q2) + u2*cos(q3)))*(u1*sin(q2) + u3)) - b*g*mass*(sin(q1)*sin(q3) - sin(q2)*cos(q1)*cos(q3)) - b*mass*(b*u1*u2*cos(q2) - l*(u1*u2*sin(q2)*sin(q3) - u1*u3*cos(q2)*cos(q3) - u2*u3*sin(q3)) - (-a*(u1*sin(q2) + u3) + l*(u1*cos(q2)*cos(q3) + u2*sin(q3)))*(u1*sin(q2) + u3) + (a*(-u1*sin(q3)*cos(q2) + u2*cos(q3)) - b*(u1*cos(q2)*cos(q3) + u2*sin(q3)))*(-u1*sin(q3)*cos(q2) + u2*cos(q3))) - c3*u3 + (-u1*sin(q3)*cos(q2) + u2*cos(q3))*(IBxx*(u1*cos(q2)*cos(q3) + u2*sin(q3)) + IBxy*(-u1*sin(q3)*cos(q2) + u2*cos(q3)) + IBzx*(u1*sin(q2) + u3)) - (u1*cos(q2)*cos(q3) + u2*sin(q3))*(IBxy*(u1*cos(q2)*cos(q3) + u2*sin(q3)) + IByy*(-u1*sin(q3)*cos(q2) + u2*cos(q3)) + IByz*(u1*sin(q2) + u3))];

R = mm\fo;
xd(1) = R(1);
xd(2) = R(2);
xd(3) = R(3);
xd(4) = R(4);
xd(5) = R(5);
xd(6) = R(6);