function dydt = myfun(t,in2)
%MYFUN
%    DYDT = MYFUN(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    06-Feb-2024 18:45:29

y1 = in2(1,:);
y2 = in2(2,:);
dydt = [y2;-y1-y2.*(y1.^2-1.0)];
end
