function angles = XYZ_angles(in1)
%XYZ_angles
%    ANGLES = XYZ_angles(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    06-Jun-2024 18:19:14

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
q5 = in1(5,:);
q6 = in1(6,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = cos(q4);
t6 = cos(q5);
t7 = cos(q6);
t8 = sin(q1);
t9 = sin(q2);
t10 = sin(q3);
t11 = sin(q4);
t12 = sin(q5);
t13 = sin(q6);
t14 = t3.*t4.*t12;
t15 = t5.*t6.*t9;
t16 = t3.*t6.*t10.*t11;
t17 = t14+t15+t16;
t18 = t17.^2;
t19 = -t18;
t20 = t19+1.0;
t21 = 1.0./sqrt(t20);
angles = [atan2(t21.*(-t12.*(t2.*t10+t4.*t8.*t9)+t6.*t11.*(t2.*t4-t8.*t9.*t10)+t3.*t5.*t6.*t8),t21.*(t12.*(t8.*t10-t2.*t4.*t9)-t6.*t11.*(t4.*t8+t2.*t9.*t10)+t2.*t3.*t5.*t6));asin(t17);atan2(t21.*(-t9.*(t7.*t11+t5.*t12.*t13)+t3.*t10.*(t5.*t7-t11.*t12.*t13)+t3.*t4.*t6.*t13),t21.*(t9.*(t11.*t13-t5.*t7.*t12)-t3.*t10.*(t5.*t13+t7.*t11.*t12)+t3.*t4.*t6.*t7))];
end
